set_property IOSTANDARD LVCMOS33 [get_ports I[0]]
set_property IOSTANDARD LVCMOS33 [get_ports I[1]]
set_property IOSTANDARD LVCMOS33 [get_ports I[2]]
set_property IOSTANDARD LVCMOS33 [get_ports I[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Q[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Q[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Q[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Q[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Q[4]]
set_property IOSTANDARD LVCMOS33 [get_ports Q[5]]
set_property IOSTANDARD LVCMOS33 [get_ports Q[6]]
set_property IOSTANDARD LVCMOS33 [get_ports Q[7]]

set_property PACKAGE_PIN L1 [get_ports Q[0]]
set_property PACKAGE_PIN P1 [get_ports Q[1]]
set_property PACKAGE_PIN N3 [get_ports Q[2]]
set_property PACKAGE_PIN P3 [get_ports Q[3]]
set_property PACKAGE_PIN U3 [get_ports Q[4]]
set_property PACKAGE_PIN W3 [get_ports Q[5]]
set_property PACKAGE_PIN V3 [get_ports Q[6]]
set_property PACKAGE_PIN V13 [get_ports Q[7]]

set_property PACKAGE_PIN T2 [get_ports I[0]]
set_property PACKAGE_PIN T3 [get_ports I[1]]
set_property PACKAGE_PIN V2 [get_ports I[2]]
